spring:
  application:
    name: music-product-api
  flyway:
#    locations:
#      - classpath:db/migration
#    group: true
    enabled: true
  datasource:
    url: jdbc:postgresql://music-product-db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
#    hibernate:
#      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect